apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-master
  name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - name: spark-master
        image: ppatierno/spark:2.0
        imagePullPolicy: "Always"
        command: ["/start-master.sh"]
        ports:
          - containerPort: 7077
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
