apiVersion: v1
kind: Service
metadata:
  labels:
    name: spark-master
  name: spark-master
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: spark
    port: 7077
    targetPort: 7077
  selector:
    name: spark-master
